## Дз к уроку 5

Найти SVD для матрицы

In [1]:
import numpy as np
np.set_printoptions(precision=2)

In [2]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [1, 0, 0]])
print(f'Матрица А:\n{A}')

Матрица А:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 1  0  0]]


In [3]:
U, s, W = np.linalg.svd(A)
print(f'U:\n{U}\ns:\n{s}\nW:\n{W}')

U:
[[ 0.17  0.16 -0.51 -0.76 -0.33]
 [ 0.4  -0.52  0.6  -0.45  0.09]
 [-0.14 -0.83 -0.46  0.19 -0.19]
 [ 0.89  0.08 -0.24  0.38 -0.02]
 [ 0.01 -0.06 -0.34 -0.18  0.92]]
s:
[8.8  6.12 2.69]
W:
[[ 0.07  0.71  0.7 ]
 [-0.38  0.67 -0.64]
 [-0.92 -0.22  0.32]]


In [4]:
V = W.T

D = np.zeros_like(V, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [5]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.8  0.   0.  ]
 [0.   6.12 0.  ]
 [0.   0.   2.69]]


In [6]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.51 -0.76 -0.33]
 [ 0.4  -0.52  0.6  -0.45  0.09]
 [-0.14 -0.83 -0.46  0.19 -0.19]
 [ 0.89  0.08 -0.24  0.38 -0.02]
 [ 0.01 -0.06 -0.34 -0.18  0.92]]


In [7]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.38 -0.92]
 [ 0.71  0.67 -0.22]
 [ 0.7  -0.64  0.32]]


Найти Евклидову и Фрабениуса нормы для матрицы А

In [34]:
euclid_norm = np.linalg.norm(A, ord=2) #Евклидова норма
print(f'{euclid_norm:.2f}')

8.80


In [32]:
euclid_norm == s[0]

True

In [44]:
frob_norm_1 = np.linalg.norm(A)
print(f'Норма Фробениуса:\n{frob_norm_1:.2f}')#Это норма Фробениуса

Норма Фробениуса:
11.05


In [43]:
frob_norm_2 = (sum(i**2 for i in s))**0.5
print(f'Норма Фробениуса:\n{frob_norm_2:.2f}')#то же самое из сингулярности

Норма Фробениуса:
11.05


In [79]:
frob_norm_3 = (sum(sum(i**2 for i in A.reshape(1, 15))))**0.5
print(f'Норма Фробениуса:\n{frob_norm_3:.2f}')#то же чсамое из исходной матрицы

Норма Фробениуса:
11.05


In [86]:
print(f'норма Фробениуса из питона:\n\t{frob_norm_1}\nиз сингулярности:\n\t{frob_norm_2}\n'
      f'из исходной матрицы:\n\t{frob_norm_3}')

норма Фробениуса из питона:
	11.045361017187261
из сингулярности:
	11.045361017187263
из исходной матрицы:
	11.045361017187261


In [88]:
print(f'{frob_norm_3:.2f}' == f'{frob_norm_2:.2f}' == f'{frob_norm_1:.2f}')

True


Спасибо вам большое. Вы всегда интересно, логично и понятно объясняете материал, делать домашку после такой лекции очень приятно. 
Хочу извиниться за то что редко был на вебинарах - работаю сутками, поэтому почти никогда не совпадаю по расписанию с он-лайн уроками.
Надеюсь, еще увидимся. 